#+title: Budgeting
#+options: toc:nil


* Definitions

Notes on a proposed system of personal finance which (a) is equivalent
to double-entry book-keeping; (b) has transactions as primary, rather
than accounts; (c) has some advantages for budgeting. 

1. Fix, once and for all, a finite set, $\mathcal{P}$, of /persons/,
   representing the people and institutions in the world who might
   receive or provide goods, services, or favours to me. We assume
   that there is a distinguished member of $\mathcal{P}$ called
   “Self.”

2. A /period/ is a pair of dates, $t_1$ and $t_2$, such that
   $t_1\leqslant t_2$. Either date may be one of the two special
   values “some day” or “any day.”

   A period represents the time during which a transaction may have
   occured. 

3. A /favour/ is
   1. an ordered pair, $(i, j)$, of people, $i,j\in \mathcal{P}$; 
   2. a non-negative number, $v$; and
   3. a period, $T$.

   A favour represents the provision of a good or service, of value
   $v$, to $j$ by $i$, sometime in period $T$. Person $i$ is called
   the /creditor/ and person $j$ the /debtor/.  We sometimes write the
   favour as $i \overset{v}{\to} j$, ignoring the period.

   For $k$ a person, we define the /credit value/ of a favour to $k$ as
   \begin{equation*}
   \pi_k^{\text Cr}(i\overset{v}{\to}j) =
   \begin{cases}
   v &\text{if $k = i$,} \\
   0 & \text{otherwise,}
   \end{cases}
   \end{equation*}
   and likewise the /debit value/ of a favour to $k$ is
   \begin{equation*}
   \pi_k^{\text Dr}(i\overset{v}{\to}j) =
   \begin{cases}
   v &\text{if $k = j$,} \\
   0 & \text{otherwise.}
   \end{cases}
   \end{equation*}
   
4. A /transaction/ is a set of favours, $f_n$, such that:
   \begin{equation*}
   \sum_n  \pi_k^{\text Cr}(f_n) = \sum_n \pi_k^{\text Dr}(f_n)
   \qquad(\forall k\in\mathcal{P}).
   \end{equation*}
   That is, in any transaction each person enters equally as a
   creditor and a debtor. (Note that this constraint applies
   separately to each person but does not mention time.)

5. An /account/ is a set of transactions.


** Examples

*** Example 1

/Dramatis personae:/ Self, Bob.

Bob gives me an apple today, in return for which, I agree to wash
Bob's window tomorrow, which I do. In the market, apples cost £1, as
do windows washed.

There is a single transaction, consisting of two favours which occur
at different times:
1. Favour 1: £1, (Bob, Self), (day 0, day 0)
2. Favour 2: £1, (Self, Bob), (day 1, day 1)

*** Example 2

/Dramatis personae:/ Self, Sainsburys, My Cash.

I buy an apple from the supermarket for cash.

There is a single transaction, consisting of three favours which occur simultaneously:

1. Favour 1: £1, (Sainsburys, Self)
2. Favour 2: £1, (My Cash, Sainsburys)
3. Favour 3: £1, (Self, My Cash)






*** ACT II

/Dramatis personae:/ Me, Bob, Anna.

I wash Anna's window today. Bob gives me an apple tomorrow. I tell
Anna to owe Bob.

Self-directed transaction:
- Today: £1: Anna; Someday: -£1: Anna.
- Tomorrow: -£1: Bob; Someday: £1: Bob
- 

  
** Versions

The main thing I wanted to achieve was to replace the idea of assets
and liabilities with the idea of "transactions that will occur in the
future, only we don't know when".

After all, transactions that will definitely occur are "scheduled
payments", or "scheduled income". (Although ... there is this idea of
capitalising future cashflows?) 

One thing unresolved is how to move an obligation (a future favour?)
from one entity to another. 

